In [1]:
import pandas as pd
import numpy as np
import os
import re
import string
import nltk
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from transformers import BertTokenizer, BertForSequenceClassification, get_linear_schedule_with_warmup, BertModel, DataCollatorWithPadding
from torch.utils.data import DataLoader, Dataset, random_split
import torch
from tqdm import tqdm
import logging
import torch.nn as nn
import torch.optim as optim
from torch.optim import AdamW
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
from transformers import LongformerForSequenceClassification
from transformers import LongformerTokenizer
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from transformers import LongformerModel, LongformerConfig

In [2]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
class SimpleBertDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=256):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = float(self.labels[idx])
        encoded = self.tokenizer(
            text,
            truncation=True,
            padding='max_length',
            max_length=self.max_length,
            return_tensors='pt'
        )
        return {
            'input_ids': encoded['input_ids'].squeeze(0),
            'attention_mask': encoded['attention_mask'].squeeze(0),
            'label': torch.tensor(label, dtype=torch.float)
        }

In [4]:
def train_one_epoch(model, dataloader, criterion, optimizer, device, scheduler):
    model.train()
    total_loss, total, correct = 0.0, 0, 0
    pbar = tqdm(dataloader, desc="Training", ncols=120)
    for batch in pbar:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)

        optimizer.zero_grad()
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        logits = outputs.logits.view(-1)
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()
        scheduler.step()

        total_loss += loss.item() * len(labels)
        preds = (torch.sigmoid(logits) >= 0.5).float()
        correct += (preds == labels).sum().item()
        total += len(labels)
        pbar.set_postfix({
            'loss': total_loss / total if total > 0 else 0,
            'acc': 100.0 * correct / total if total > 0 else 0
        })
    avg_loss = total_loss / total
    avg_acc = 100.0 * correct / total
    print(f"[Train] Loss: {avg_loss:.4f} | Accuracy: {avg_acc:.2f}%")
    return avg_loss, avg_acc

In [5]:
def evaluate(model, dataloader, criterion, device):
    model.eval()
    total_loss, total, correct = 0.0, 0, 0
    all_preds, all_labels = [], []
    pbar = tqdm(dataloader, desc="Validating", ncols=120)
    with torch.no_grad():
        for batch in pbar:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['label'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = outputs.logits.view(-1)
            loss = criterion(logits, labels)

            total_loss += loss.item() * len(labels)
            preds = (torch.sigmoid(logits) >= 0.5).float()
            correct += (preds == labels).sum().item()
            total += len(labels)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
            pbar.set_postfix({
                'val_loss': total_loss / total if total > 0 else 0,
                'val_acc': 100.0 * correct / total if total > 0 else 0
            })
    avg_loss = total_loss / total
    avg_acc = 100.0 * correct / total
    print(f"[Valid] Loss: {avg_loss:.4f} | Accuracy: {avg_acc:.2f}%")
    return avg_loss, avg_acc, all_preds, all_labels

In [6]:
def get_predictions(model, data_loader, device):
    """
    Returns:
        - preds: Predicted class labels (0 or 1)
        - labels: True class labels (0 or 1)
        - probs: Sigmoid probabilities (float)
    """
    model.eval()
    all_preds = []
    all_labels = []
    all_probs = []
    from tqdm import tqdm
    with torch.no_grad():
        for batch in tqdm(data_loader, desc="Predicting", ncols=120):
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['label'].to(device)
            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = outputs.logits.view(-1)
            probs = torch.sigmoid(logits)
            preds = (probs >= 0.5).long()
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())
    return np.array(all_preds), np.array(all_labels), np.array(all_probs)


In [7]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=1)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e

In [8]:
# 0.733145
mimic_train = pd.read_csv('/content/drive/My Drive/EHR_PROJ/DATA/new_berkeley_train.csv')
mimic_test = pd.read_csv('/content/drive/My Drive/EHR_PROJ/DATA/new_berkeley_test.csv')

In [9]:
train_texts = mimic_train['text'].astype(str).tolist()
train_labels = mimic_train['labels'].tolist()
val_texts = mimic_test['text'].astype(str).tolist()
val_labels = mimic_test['labels'].tolist()

In [10]:
train_dataset = SimpleBertDataset(train_texts, train_labels, tokenizer, max_length=128)
val_dataset = SimpleBertDataset(val_texts, val_labels, tokenizer, max_length=128)
train_loader = DataLoader(train_dataset, batch_size=256, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=256, shuffle=False)

In [11]:
# Define the optimizer and loss function
num_epochs = 12
# Calculate class counts
#num_negative = (np.array(train_labels) == 0).sum()
#num_positive = (np.array(train_labels) == 1).sum()
#pos_weight = torch.tensor([num_negative / num_positive * 1.2], dtype=torch.float).to(device)
#print(f"num_negative: {num_negative}, num_positive: {num_positive}, pos_weight: {pos_weight.item():.2f}")
#model.config.attention_probs_dropout_prob = 0.2  # Increasing attention dropout to 0.2
#model.config.hidden_dropout_prob = 0.2  # Increasing hidden dropout to 0.2
optimizer = optim.AdamW(model.parameters(), lr=1e-5)
#criterion = torch.nn.BCEWithLogitsLoss(pos_weight=pos_weight)
criterion = torch.nn.BCEWithLogitsLoss()
total_steps = len(train_loader) * num_epochs
scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=0, num_training_steps=total_steps)

In [12]:
save_directory_model = '/content/drive/My Drive/EHR_PROJ/MODELS/bert_hate_0522'
os.makedirs(save_directory_model, exist_ok=True)

In [13]:
best_val_accuracy = 0.0

for epoch in range(num_epochs):
    print(f'Epoch [{epoch + 1}/{num_epochs}]')
    train_loss, train_accuracy = train_one_epoch(model, train_loader, criterion, optimizer, device, scheduler)
    print(f'Training Loss: {train_loss:.4f}, Training Accuracy: {train_accuracy:.2f}%')

    val_loss, val_accuracy, _, _ = evaluate(model, val_loader, criterion, device)
    print(f'Validation Loss: {val_loss:.4f}, Validation Accuracy: {val_accuracy:.2f}%')

    # Save the model only if the validation accuracy has improved
    if val_accuracy > best_val_accuracy:
        best_val_accuracy = val_accuracy
        model.save_pretrained(save_directory_model)
        tokenizer.save_pretrained(save_directory_model)
        print(f"Model saved at epoch {epoch + 1} with improved validation accuracy: {val_accuracy:.2f}%")

        # Get predictions on the combined validation set (no pooling needed)
        predictions, true_labels, _ = get_predictions(model, val_loader, device)

        # Calculate confusion matrix
        cm = confusion_matrix(true_labels, predictions)
        print("Confusion Matrix:")
        print(cm)

        # Calculate precision, recall, F1-score
        report = classification_report(true_labels, predictions, digits=3)
        print("Classification Report:")
        print(report)


Epoch [1/12]


Training: 100%|███████████████████████████████████████████████████| 87/87 [01:45<00:00,  1.21s/it, loss=0.494, acc=75.2]


[Train] Loss: 0.4943 | Accuracy: 75.15%
Training Loss: 0.4943, Training Accuracy: 75.15%


Validating: 100%|█████████████████████████████████████████| 22/22 [00:11<00:00,  1.99it/s, val_loss=0.351, val_acc=84.8]


[Valid] Loss: 0.3507 | Accuracy: 84.78%
Validation Loss: 0.3507, Validation Accuracy: 84.78%
Model saved at epoch 1 with improved validation accuracy: 84.78%


Predicting: 100%|███████████████████████████████████████████████████████████████████████| 22/22 [00:11<00:00,  1.96it/s]


Confusion Matrix:
[[3123  400]
 [ 447 1595]]
Classification Report:
              precision    recall  f1-score   support

         0.0      0.875     0.886     0.881      3523
         1.0      0.799     0.781     0.790      2042

    accuracy                          0.848      5565
   macro avg      0.837     0.834     0.835      5565
weighted avg      0.847     0.848     0.847      5565

Epoch [2/12]


Training: 100%|███████████████████████████████████████████████████| 87/87 [01:45<00:00,  1.21s/it, loss=0.314, acc=86.5]


[Train] Loss: 0.3145 | Accuracy: 86.51%
Training Loss: 0.3145, Training Accuracy: 86.51%


Validating: 100%|█████████████████████████████████████████| 22/22 [00:11<00:00,  2.00it/s, val_loss=0.312, val_acc=86.3]


[Valid] Loss: 0.3118 | Accuracy: 86.25%
Validation Loss: 0.3118, Validation Accuracy: 86.25%
Model saved at epoch 2 with improved validation accuracy: 86.25%


Predicting: 100%|███████████████████████████████████████████████████████████████████████| 22/22 [00:11<00:00,  2.00it/s]


Confusion Matrix:
[[3103  420]
 [ 345 1697]]
Classification Report:
              precision    recall  f1-score   support

         0.0      0.900     0.881     0.890      3523
         1.0      0.802     0.831     0.816      2042

    accuracy                          0.863      5565
   macro avg      0.851     0.856     0.853      5565
weighted avg      0.864     0.863     0.863      5565

Epoch [3/12]


Training: 100%|███████████████████████████████████████████████████| 87/87 [01:45<00:00,  1.21s/it, loss=0.267, acc=88.9]


[Train] Loss: 0.2669 | Accuracy: 88.88%
Training Loss: 0.2669, Training Accuracy: 88.88%


Validating: 100%|█████████████████████████████████████████| 22/22 [00:11<00:00,  1.99it/s, val_loss=0.307, val_acc=87.1]


[Valid] Loss: 0.3066 | Accuracy: 87.12%
Validation Loss: 0.3066, Validation Accuracy: 87.12%
Model saved at epoch 3 with improved validation accuracy: 87.12%


Predicting: 100%|███████████████████████████████████████████████████████████████████████| 22/22 [00:11<00:00,  1.99it/s]


Confusion Matrix:
[[3216  307]
 [ 410 1632]]
Classification Report:
              precision    recall  f1-score   support

         0.0      0.887     0.913     0.900      3523
         1.0      0.842     0.799     0.820      2042

    accuracy                          0.871      5565
   macro avg      0.864     0.856     0.860      5565
weighted avg      0.870     0.871     0.870      5565

Epoch [4/12]


Training: 100%|███████████████████████████████████████████████████| 87/87 [01:45<00:00,  1.21s/it, loss=0.237, acc=90.4]


[Train] Loss: 0.2367 | Accuracy: 90.44%
Training Loss: 0.2367, Training Accuracy: 90.44%


Validating: 100%|█████████████████████████████████████████| 22/22 [00:11<00:00,  1.99it/s, val_loss=0.307, val_acc=87.1]


[Valid] Loss: 0.3069 | Accuracy: 87.13%
Validation Loss: 0.3069, Validation Accuracy: 87.13%
Model saved at epoch 4 with improved validation accuracy: 87.13%


Predicting: 100%|███████████████████████████████████████████████████████████████████████| 22/22 [00:11<00:00,  1.93it/s]


Confusion Matrix:
[[3124  399]
 [ 317 1725]]
Classification Report:
              precision    recall  f1-score   support

         0.0      0.908     0.887     0.897      3523
         1.0      0.812     0.845     0.828      2042

    accuracy                          0.871      5565
   macro avg      0.860     0.866     0.863      5565
weighted avg      0.873     0.871     0.872      5565

Epoch [5/12]


Training: 100%|███████████████████████████████████████████████████| 87/87 [01:45<00:00,  1.21s/it, loss=0.209, acc=91.5]


[Train] Loss: 0.2090 | Accuracy: 91.48%
Training Loss: 0.2090, Training Accuracy: 91.48%


Validating: 100%|█████████████████████████████████████████| 22/22 [00:11<00:00,  1.99it/s, val_loss=0.309, val_acc=87.5]


[Valid] Loss: 0.3094 | Accuracy: 87.53%
Validation Loss: 0.3094, Validation Accuracy: 87.53%
Model saved at epoch 5 with improved validation accuracy: 87.53%


Predicting: 100%|███████████████████████████████████████████████████████████████████████| 22/22 [00:11<00:00,  1.99it/s]


Confusion Matrix:
[[3200  323]
 [ 371 1671]]
Classification Report:
              precision    recall  f1-score   support

         0.0      0.896     0.908     0.902      3523
         1.0      0.838     0.818     0.828      2042

    accuracy                          0.875      5565
   macro avg      0.867     0.863     0.865      5565
weighted avg      0.875     0.875     0.875      5565

Epoch [6/12]


Training: 100%|███████████████████████████████████████████████████| 87/87 [01:45<00:00,  1.21s/it, loss=0.178, acc=93.3]


[Train] Loss: 0.1783 | Accuracy: 93.30%
Training Loss: 0.1783, Training Accuracy: 93.30%


Validating: 100%|█████████████████████████████████████████| 22/22 [00:11<00:00,  1.99it/s, val_loss=0.323, val_acc=87.6]


[Valid] Loss: 0.3234 | Accuracy: 87.60%
Validation Loss: 0.3234, Validation Accuracy: 87.60%
Model saved at epoch 6 with improved validation accuracy: 87.60%


Predicting: 100%|███████████████████████████████████████████████████████████████████████| 22/22 [00:11<00:00,  2.00it/s]


Confusion Matrix:
[[3198  325]
 [ 365 1677]]
Classification Report:
              precision    recall  f1-score   support

         0.0      0.898     0.908     0.903      3523
         1.0      0.838     0.821     0.829      2042

    accuracy                          0.876      5565
   macro avg      0.868     0.865     0.866      5565
weighted avg      0.876     0.876     0.876      5565

Epoch [7/12]


Training: 100%|█████████████████████████████████████████████████████| 87/87 [01:45<00:00,  1.21s/it, loss=0.158, acc=94]


[Train] Loss: 0.1579 | Accuracy: 94.00%
Training Loss: 0.1579, Training Accuracy: 94.00%


Validating: 100%|█████████████████████████████████████████| 22/22 [00:11<00:00,  1.99it/s, val_loss=0.347, val_acc=87.7]


[Valid] Loss: 0.3467 | Accuracy: 87.71%
Validation Loss: 0.3467, Validation Accuracy: 87.71%
Model saved at epoch 7 with improved validation accuracy: 87.71%


Predicting: 100%|███████████████████████████████████████████████████████████████████████| 22/22 [00:11<00:00,  1.99it/s]


Confusion Matrix:
[[3240  283]
 [ 401 1641]]
Classification Report:
              precision    recall  f1-score   support

         0.0      0.890     0.920     0.905      3523
         1.0      0.853     0.804     0.828      2042

    accuracy                          0.877      5565
   macro avg      0.871     0.862     0.866      5565
weighted avg      0.876     0.877     0.876      5565

Epoch [8/12]


Training: 100%|█████████████████████████████████████████████████████| 87/87 [01:45<00:00,  1.21s/it, loss=0.139, acc=95]


[Train] Loss: 0.1392 | Accuracy: 95.02%
Training Loss: 0.1392, Training Accuracy: 95.02%


Validating: 100%|██████████████████████████████████████████| 22/22 [00:11<00:00,  1.99it/s, val_loss=0.36, val_acc=87.5]


[Valid] Loss: 0.3604 | Accuracy: 87.53%
Validation Loss: 0.3604, Validation Accuracy: 87.53%
Epoch [9/12]


Training: 100%|███████████████████████████████████████████████████| 87/87 [01:45<00:00,  1.21s/it, loss=0.123, acc=95.8]


[Train] Loss: 0.1226 | Accuracy: 95.75%
Training Loss: 0.1226, Training Accuracy: 95.75%


Validating: 100%|█████████████████████████████████████████| 22/22 [00:11<00:00,  1.99it/s, val_loss=0.375, val_acc=87.6]


[Valid] Loss: 0.3745 | Accuracy: 87.62%
Validation Loss: 0.3745, Validation Accuracy: 87.62%
Epoch [10/12]


Training: 100%|█████████████████████████████████████████████████████| 87/87 [01:45<00:00,  1.21s/it, loss=0.113, acc=96]


[Train] Loss: 0.1130 | Accuracy: 95.97%
Training Loss: 0.1130, Training Accuracy: 95.97%


Validating: 100%|█████████████████████████████████████████| 22/22 [00:11<00:00,  1.99it/s, val_loss=0.381, val_acc=87.4]


[Valid] Loss: 0.3812 | Accuracy: 87.44%
Validation Loss: 0.3812, Validation Accuracy: 87.44%
Epoch [11/12]


Training: 100%|███████████████████████████████████████████████████| 87/87 [01:45<00:00,  1.21s/it, loss=0.105, acc=96.4]


[Train] Loss: 0.1047 | Accuracy: 96.41%
Training Loss: 0.1047, Training Accuracy: 96.41%


Validating: 100%|█████████████████████████████████████████| 22/22 [00:11<00:00,  1.99it/s, val_loss=0.388, val_acc=87.5]


[Valid] Loss: 0.3876 | Accuracy: 87.49%
Validation Loss: 0.3876, Validation Accuracy: 87.49%
Epoch [12/12]


Training: 100%|███████████████████████████████████████████████████| 87/87 [01:45<00:00,  1.21s/it, loss=0.101, acc=96.6]


[Train] Loss: 0.1005 | Accuracy: 96.60%
Training Loss: 0.1005, Training Accuracy: 96.60%


Validating: 100%|█████████████████████████████████████████| 22/22 [00:11<00:00,  1.99it/s, val_loss=0.389, val_acc=87.5]

[Valid] Loss: 0.3892 | Accuracy: 87.48%
Validation Loss: 0.3892, Validation Accuracy: 87.48%
